import type { AssessmentHistory, AssessmentResult } from '@/types';

export const MOCK_ASSESSMENT_HISTORY: AssessmentHistory[] = [
  {
    id: 'hist-1',
    topicName: 'Python Basics',
    date: '2026-06-10T10:30:00Z',
    duration: 540,
    score: 92,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-2',
    topicName: 'Functions',
    date: '2026-06-08T14:00:00Z',
    duration: 480,
    score: 85,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-3',
    topicName: 'Object-Oriented Programming',
    date: '2026-06-05T09:15:00Z',
    duration: 600,
    score: 50,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-4',
    topicName: 'Decorators',
    date: '2026-06-03T16:45:00Z',
    duration: 420,
    score: 20,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-5',
    topicName: 'Data Structures',
    date: '2026-05-28T11:00:00Z',
    duration: 360,
    score: 75,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-6',
    topicName: 'Algorithms',
    date: '2026-05-25T13:30:00Z',
    duration: 540,
    score: 68,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-7',
    topicName: 'React Basics',
    date: '2026-05-22T10:15:00Z',
    duration: 480,
    score: 88,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-8',
    topicName: 'SQL & Databases',
    date: '2026-05-20T15:45:00Z',
    duration: 600,
    score: 72,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-9',
    topicName: 'JavaScript Fundamentals',
    date: '2026-05-18T09:30:00Z',
    duration: 420,
    score: 80,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-10',
    topicName: 'TypeScript',
    date: '2026-05-15T14:00:00Z',
    duration: 480,
    score: 76,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-11',
    topicName: 'Git & Version Control',
    date: '2026-05-12T11:30:00Z',
    duration: 300,
    score: 94,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-12',
    topicName: 'REST APIs',
    date: '2026-05-10T10:00:00Z',
    duration: 540,
    score: 82,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-13',
    topicName: 'HTML & CSS',
    date: '2026-05-08T13:15:00Z',
    duration: 360,
    score: 89,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-14',
    topicName: 'Node.js',
    date: '2026-05-05T09:45:00Z',
    duration: 600,
    score: 78,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-15',
    topicName: 'MongoDB & NoSQL',
    date: '2026-05-02T14:30:00Z',
    duration: 480,
    score: 71,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-16',
    topicName: 'Docker & Containerization',
    date: '2026-04-30T10:15:00Z',
    duration: 540,
    score: 65,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-17',
    topicName: 'Kubernetes Basics',
    date: '2026-04-28T15:00:00Z',
    duration: 600,
    score: 58,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-18',
    topicName: 'AWS Cloud Services',
    date: '2026-04-25T11:45:00Z',
    duration: 480,
    score: 73,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-19',
    topicName: 'GraphQL',
    date: '2026-04-22T09:30:00Z',
    duration: 420,
    score: 79,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-20',
    topicName: 'Testing & QA',
    date: '2026-04-20T14:15:00Z',
    duration: 360,
    score: 84,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-21',
    topicName: 'Design Patterns',
    date: '2026-04-18T10:30:00Z',
    duration: 540,
    score: 81,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-22',
    topicName: 'Microservices Architecture',
    date: '2026-04-15T13:45:00Z',
    duration: 600,
    score: 69,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-23',
    topicName: 'Web Security',
    date: '2026-04-12T09:00:00Z',
    duration: 480,
    score: 86,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-24',
    topicName: 'Performance Optimization',
    date: '2026-04-10T15:30:00Z',
    duration: 420,
    score: 77,
    totalScore: 100,
    status: 'completed',
  },
  {
    id: 'hist-25',
    topicName: 'Agile & Scrum',
    date: '2026-04-08T11:15:00Z',
    duration: 300,
    score: 91,
    totalScore: 100,
    status: 'completed',
  },
];

export const MOCK_RESULT: AssessmentResult = {
  id: 'result-mock',
  topicId: 'python-basics',
  topicName: 'Python Basics',
  date: new Date().toISOString(),
  duration: 845,
  score: 79,
  totalScore: 100,
  status: 'completed',
  skillScores: [
    { skill: 'Python Fundamentals', score: 90, maxScore: 100, level: 'advanced' },
    { skill: 'Functions', score: 85, maxScore: 100, level: 'intermediate' },
    { skill: 'Object-Oriented Programming', score: 50, maxScore: 100, level: 'beginner' },
    { skill: 'Decorators', score: 20, maxScore: 100, level: 'beginner' },
    { skill: 'Data Structures', score: 75, maxScore: 100, level: 'intermediate' },
    { skill: 'Algorithms', score: 68, maxScore: 100, level: 'intermediate' },
    { skill: 'React Basics', score: 88, maxScore: 100, level: 'advanced' },
    { skill: 'SQL & Databases', score: 72, maxScore: 100, level: 'intermediate' },
    { skill: 'JavaScript Fundamentals', score: 80, maxScore: 100, level: 'advanced' },
    { skill: 'TypeScript', score: 76, maxScore: 100, level: 'intermediate' },
    { skill: 'Git & Version Control', score: 94, maxScore: 100, level: 'advanced' },
    { skill: 'REST APIs', score: 82, maxScore: 100, level: 'advanced' },
    { skill: 'HTML & CSS', score: 89, maxScore: 100, level: 'advanced' },
    { skill: 'Node.js', score: 78, maxScore: 100, level: 'intermediate' },
    { skill: 'MongoDB & NoSQL', score: 71, maxScore: 100, level: 'intermediate' },
    { skill: 'Docker & Containerization', score: 65, maxScore: 100, level: 'intermediate' },
    { skill: 'Kubernetes Basics', score: 58, maxScore: 100, level: 'beginner' },
    { skill: 'AWS Cloud Services', score: 73, maxScore: 100, level: 'intermediate' },
    { skill: 'GraphQL', score: 79, maxScore: 100, level: 'intermediate' },
    { skill: 'Testing & QA', score: 84, maxScore: 100, level: 'advanced' },
    { skill: 'Design Patterns', score: 81, maxScore: 100, level: 'advanced' },
    { skill: 'Microservices Architecture', score: 69, maxScore: 100, level: 'intermediate' },
    { skill: 'Web Security', score: 86, maxScore: 100, level: 'advanced' },
    { skill: 'Performance Optimization', score: 77, maxScore: 100, level: 'intermediate' },
    { skill: 'Agile & Scrum', score: 91, maxScore: 100, level: 'advanced' },
  ],
  knowledgeGaps: [
    {
      concept: 'Function Decorators',
      status: 'strength',
      description: 'Strong understanding of decorators and their use cases.',
      suggestedResources: ['Python Docs - Decorators'],
    },
    {
      concept: 'Class Inheritance',
      status: 'weak',
      description: 'Basic understanding but needs practice with complex hierarchies.',
      suggestedResources: ['OOP in Python Course', 'Inheritance Patterns'],
    },
    {
      concept: 'Metaclasses',
      status: 'missing',
      description: 'No knowledge of metaclasses or their applications.',
      suggestedResources: ['Python Metaclasses Guide', 'Advanced Python Book'],
    },
  ],
  roadmap: [
    {
      week: 1,
      title: 'Python Basics Review',
      description: 'Reinforce fundamentals: variables, data types, control flow',
      topics: ['Variables', 'Data Types', 'Control Flow', 'Functions'],
      status: 'completed',
      resources: ['Python Basics Tutorial', 'Practice Exercises'],
    },
    {
      week: 2,
      title: 'Functions Deep Dive',
      description: 'Master function definitions, parameters, scope, and closures',
      topics: ['Function Parameters', 'Scope', 'Closures', 'Lambda Functions'],
      status: 'in_progress',
      resources: ['Functions Guide', 'Advanced Functions'],
    },
    {
      week: 3,
      title: 'Object-Oriented Programming',
      description: 'Classes, objects, inheritance, polymorphism, encapsulation',
      topics: ['Classes', 'Inheritance', 'Polymorphism', 'Encapsulation'],
      status: 'locked',
      resources: ['OOP Concepts', 'Python OOP Tutorial'],
    },
    {
      week: 4,
      title: 'Decorators & Metaprogramming',
      description: 'Function decorators, class decorators, and metaclasses',
      topics: ['Function Decorators', 'Class Decorators', 'Metaclasses'],
      status: 'locked',
      resources: ['Decorators Guide', 'Metaprogramming in Python'],
    },
  ],
};
